### ISSUE TITLE
Error: TypeError: Cannot read properties of null (reading 'expressao')

### ISSUE THREAD

**Issue by danielluizd** [DesignLiquido/liquido#19]
Estou recebendo esse erro ao tentar executar liquido (já adicionei o repositório de rotas com o inicial.delegua dentro)
![image](https://user-images.githubusercontent.com/84820610/221656541-4a9773ce-ec89-43b2-8380-13a476565bc2.png)

**Comment by danielluizd** [comment]
```warning ..\..\..\..\..\package.json: No license field
$ node ./node_modules/liquido/index.js
Arquivo 'configuracao.delegua' não encontrado.
C:\Users\Daniel\Documents\Daniel\desing-liquido\estudos\liquido\node_modules\liquido\liquido.js:209
            throw new Error(erro);
                  ^

Error: TypeError: Cannot read properties of null (reading 'expressao')
    at Liquido.importarArquivosRotas (C:\Users\Daniel\Documents\Daniel\desing-liquido\estudos\liquido\node_modules\liquido\liquido.js:209:19)
    at Liquido.iniciar (C:\Users\Daniel\Documents\Daniel\desing-liquido\estudos\liquido\node_modules\liquido\liquido.js:58:14)
    at Object.<anonymous> (C:\Users\Daniel\Documents\Daniel\desing-liquido\estudos\liquido\node_modules\liquido\index.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by ItaloCobains** [comment]
@danielluizd liquido depende de um arquivo de configuração chamado `configuracao.delegua`. Por padrão liquido busca por ele na raiz do seu projeto.

Nesse arquivo você pode configurar basicamente tudo na sua aplicação como arquivos estáticos, middlewares, banco de dados e tecnologias.

Exemplo:
```js
// Configuração de arquivos estáticos
liquido.roteador.diretorioEstatico = 'publico'

// Configuração do roteador.
liquido.roteador.cors = verdadeiro
liquido.roteador.bodyParser = verdadeiro
liquido.roteador.morgan = verdadeiro
liquido.roteador.cookieParser = verdadeiro
liquido.roteador.passport = verdadeiro
liquido.roteador.json = verdadeiro
liquido.roteador.helmet = verdadeiro

// Configuração de bases de dados
liquido.dados.lincones.tecnologia = 'sqlite'
liquido.dados.lincones.caminho = ':memory:'

liquido.autenticacao.tecnologia = 'jwt'

``` 

Teste implementar essa solução caso o erro persistir favor me informar.

**Comment by ItaloCobains** [comment]
@danielluizd a sintaxe usada no seu `rotas/inicial.delegua` está incorreta.

Tente isso.
```js
liquido.rotaGet(funcao(requisicao, resposta) {
  resposta.enviar("Teste de execução").status(200)
})
```
